import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeContext from "@/providers/theme-provider";
import QueryProvider from "@/providers/query-client";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-background">
        <Toaster richColors position="top-right" />
        <QueryProvider>
          <ThemeContext>{children}</ThemeContext>
        </QueryProvider>
      </body>
    </html>
  );
}
