const PRODUCT_DATA = {
  LAMA: [
    'YSL BLACK OPIUM',
    'BACARAT',
    'RUBI RAINER',
    'MEVA',
    'REXTASE',
    'B.OUTSIDE',
    '212 SEXY MAN',
    '212 SEXY WOMEN',
    '212 VIP MAN',
    'AGNES MONICA',
    'AIGNER BLACK',
    'AIGNER BLUE',
    'AIGNER DEBUT',
    'ALPHARD',
    'AMOR wOMAN',
    'ANGEL HEART',
    'ANNASUI DOLLY',
    'ANNASUI DREAM',
    'ANNASUI FANCY',
    'ANNASUI ROSE',
    'ANNASUI SECRET',
    'ANTONIO BANDERAS',
    'AQUA DE GIO MAN',
    'AQUA KISS',
    'AQUA MAN',
    'ARIANA GRANDE',
    'ARSENIK MAN',
    'AVRIL LAVIGNE',
    'AVRIL ROSE',
    'AYU TING TING',
    'BABA COFFE',
    'BABA ROMANCE',
    'BARCELONA',
    'BENETON PINK',
    'BLACK COFFE',
    'BLACK COMBAIN',
    'BLACK MIX',
    'BRITNEY SPEARS',
    'BS JAPANESE CHERRY',
    'BS WHITE MUSK',
    'BUBBLE GUM',
    'BULBERY LONDON',
    'BULGARI AQUA',
    'BULGARI EXTREAM',
    'BULGARI JASMIN',
    'BULGARI OMNIA',
    'BULGARI ROSE',
    'CH 212 MAN',
    'CHANNEL COCO',
    'CK BEE',
    'COKLAT',
    'CRZ PLATINUM',
    'CRISTIAN DIOR SAUVAGE',
    'CRISTINA AGUILERA',
    'CROOKED MAN FRAGRANCE',
    'CUDDLE BABY',
    'D&G IMPERACTIVE',
    'D&G IMPERIAL',
    'D&G LIGHT BLUE MAN',
    'D&G MAN',
    'DIAMOR',
    'DIAMOR WOMEN',
    'DUNHILL BLUE',
    'ESACADA MOON SPARKLE',
    'ESCADA CHERRY',
    'FERRARI BLACK',
    'FORSET',
    'FULL MAN',
    'GIORGIO ARMANI SI',
    'GREEN TEA',
    'GUCCI FLORA',
    'GUCCI GUILTY BLACK WOMAN',
    'GUCCI RUSH',
    'GUESS PINK',
    'HAPPY MAN',
    'HARAJUKU',
    'HEART BUTTON',
    'HERMES TERRE',
    'HUGO BOsS ARMY',
    'HUGO BOSS ENERGI',
    'HUGO BOSs ORANGE',
    'HUGO BOSS XX',
    'ICE COOL',
    'IMMAGINATION',
    'INCANTO SHINE',
    'INTERNITY MAN',
    'INTERNITY WOMEN',
    'ISSEY MIYAKE',
    'JAGUAR BLACK',
    'JAGUAR BLUE',
    'JAGUAR VISION',
    'JAMES BOND',
    'JAPANESE CERRY',
    'JESIKA PARKER',
    'JLO PLATINUM',
    'JLO STILL',
    'JOE MALONE ENGISH PEAR',
    'KASTURI',
    'KATTY PERRY',
    'KISS & ROSE',
    'KENZO BALI',
    'KENZO BATANG',
    'KENZO DAUN',
    'LACOSTE',
    'LALISA PINK NABOBAN',
    'LIFEBOUY',
    'LION KING',
    'LOVELY',
    'LUX',
    'MAHER ZEIN',
    'MALBORO',
    'MELON',
    'MOUNTBLANK',
    'NAGITA SLAVINA',
    'OLLA RAMLAN',
    'ONE DIRECTION',
    'PACO RABANI 1MILION',
    'PACO RABANI INVICTUS',
    'PARIS HILTON',
    'POLICE MAN',
    'POLO SPORT MAN',
    'RAFFI AHMAD',
    'ROMANWIS',
    'SCARLET SASA',
    'SELENA GOMES',
    'SEXY GRAVITY',
    'SILVER',
    'SOFT',
    'TAJ MAHAL',
    'TAYLOR SWIFT',
    'TISSUE',
    'VANILA',
    'VANILASUSU',
    'VANILLA COKLAT',
    'VERSACE VERSUS',
    'VICTORIA SECRET',
    'VS SCANDALOUS',
    'VS SO SEXY',
    'VS.BOMBSHELL',
    'VS.VANILA LACE',
    'WOMEN ICE',
    'ZARA LOVE',
    'ZARA MAN',
    'ZARA WOMAN',
  ],
  BARU: [
    'OVIUM FRAGRANCE',
    'TOP 501',
    'RUBI RAINER',
    'MEVA',
    'REXTASE',
    'B.OUTSIDE',
    'X MAN',
    'X WOMEN',
    'V MAN',
    'HONEY MOON',
    'BLACK JACK',
    'BLUE ART',
    'DEBUT',
    'ALPHA ORI',
    'SUNMORI',
    'HEART BOTTON',
    'DOLLY GIRL',
    'SWEET DREAM',
    'HANNA GLAMOUR',
    'SWEET ROSE',
    'HANNA CODE',
    'BANDERAS',
    'RBP GENTEL',
    'KISS ME',
    'ITS ME',
    'ARANDE',
    'ARK MAN',
    'AVNE',
    '& ROSES',
    'ASK THINK',
    'BABA KAHVE',
    'BARONCE',
    'BARBAR LONA',
    'BB PINK',
    'COFFE STAR',
    'BLACK IN',
    'BLACK MIX',
    'BS WOMEN',
    'JC BLOSSOM',
    'WHITE MUSK',
    'BUBBLE BE',
    'B LONDON',
    'BA MAN',
    'BA EXTREAM',
    'BA JASMIN',
    'BA OMNIA',
    'BA ROSE',
    'CH 2 MAN',
    'COCO',
    'SWEET BEE',
    'COKLAT',
    'CRZP',
    'CRISDI SAUVAGE',
    'CA WOME',
    'CROOKED MAN',
    'BABY FACE',
    'DETECTIVE',
    'IMPERIAL',
    'LBLUE',
    'LAKILUCK',
    'MARIMAR',
    'SAKURA',
    'BLUE SKY',
    'EX MON',
    'ESCARRY',
    'FERBLA',
    'FROSS',
    'FULL MAN',
    'GIOAR',
    'GREEN TEA',
    'G FLORA',
    'GG BLACK WOMEN',
    'G RUSH',
    'GS PINK',
    'GOOD BOY',
    'TOP JAPAN',
    'FALLING LOVE',
    'HESTER',
    'HB ARMY',
    'HB EGERGY',
    'HB ORANGE',
    'HB XX',
    'COLD MAN',
    'IMMAGINATION',
    'IN SHINE',
    'INTER MAN',
    'INTER MOWEN',
    'ISSEY MI',
    'JG BLACK',
    'JG BLUE',
    'JG VIXION',
    'BOND 7',
    'JP CERRY',
    'J PARKER',
    'JL PLATINUM',
    'JL STILL',
    'JM ENGLISH PEAR',
    'KASTURI',
    'SWEET LADY',
    'KISS & ROSE',
    'ZO BAL',
    'ZO BATANG',
    'ZO DAUN',
    'LACOST',
    'MIKA PINK',
    'LIFE BOY',
    'BLUE KING',
    'LOVE ME',
    'LUX',
    'MAIN',
    'MALB',
    'MELON',
    'MONTE BIANCO',
    'AZZURA',
    'WINTER',
    'ONE WAY',
    'PC 1 MILION',
    'PC INV',
    'EIFFEL',
    'SAFETY MAN',
    'PS MAN',
    'SUPER STAR',
    'VS SECRET',
    'SASA',
    'SELEGO',
    'SEXY GVT',
    'SILVER',
    'SOFT',
    'TAJ MAHAL',
    'SWEET BALE',
    'TISSUE',
    'VANILA',
    'VANILA SUSU',
    'SWEET CHOCOLATE',
    'VV MAN',
    'SECRET SCENT',
    'SCANDAL',
    'VS SO SEXY',
    'VS BOM SEL',
    'VS VANILA LACE',
    'WOMEN ICE',
    'ZA LOVE',
    'ZA MAN',
    'ZA WOMEN',
  ],
};

export default PRODUCT_DATA;
